# Generated by Django 4.2.10 on 2024-03-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('GBP', 'GBP'), ('Euro', 'Euro'), ('Dollar', 'Dollar')], default='GBP', max_length=20),
        ),
    ]
