# Generated by Django 4.2.10 on 2024-04-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_userprofile_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
