# Generated by Django 4.2.10 on 2024-04-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_userprofile_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('GBP', 'GBP'), ('Euro', 'EUR'), ('Dollar', 'USD')], default='GBP', max_length=20),
        ),
    ]
