# Generated by Django 4.2.10 on 2024-04-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_userprofile_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
