# Generated by Django 4.2.10 on 2024-04-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_userprofile_bank_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bank_account_number',
        ),
    ]
