# Generated by Django 4.2.10 on 2024-04-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_remove_userprofile_bank_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('GBP', 'GBP'), ('Euro', 'EUR'), ('Dollar', 'USD')], max_length=20),
        ),
    ]
