# Generated by Django 4.2.10 on 2024-04-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_alter_userprofile_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bal',
            field=models.IntegerField(default=0),
        ),
    ]
