# Generated by Django 4.2.10 on 2024-04-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
