# Generated by Django 4.2.10 on 2024-03-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bal',
            field=models.IntegerField(default=0),
        ),
    ]
