# Generated by Django 4.2.10 on 2024-04-03 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='sender',
            new_name='requester',
        ),
    ]
