# Generated by Django 4.2.10 on 2024-04-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0008_transaction_sent_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='received_currecny',
            field=models.CharField(default='', max_length=3),
        ),
    ]
