# Generated by Django 4.2.10 on 2024-04-10 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0009_transaction_received_currecny'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='received_currecny',
            new_name='received_currency',
        ),
    ]
