# Generated by Django 4.2.10 on 2024-04-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0013_alter_transaction_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('GBP', 'GBP'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=3),
        ),
    ]
