# Generated by Django 4.2.10 on 2024-04-19 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_alter_userprofile_user'),
        ('payapp', '0014_alter_userprofile_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='register.userprofile'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='register.userprofile'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
