# Generated by Django 4.2.10 on 2024-04-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0015_alter_transaction_receiver_alter_transaction_sender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='sent_amount',
        ),
    ]
