# Generated by Django 4.2.10 on 2024-04-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0017_transaction_received_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='requested_currency',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
