# Generated by Django 4.2.10 on 2024-04-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0018_notification_requested_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='sent_currency',
        ),
    ]
