# Generated by Django 4.2.10 on 2024-04-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0019_remove_transaction_sent_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sent_currency',
            field=models.CharField(default='', max_length=3),
        ),
    ]
