# Generated by Django 4.2.10 on 2024-04-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0020_transaction_sent_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
